version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: S3cret
      POSTGRES_USER: postgres
      POSTGRES_DB: acl
      DEFAULT_REDIRECT_URI: http://client-server:8080/login/oauth2/code/client-server-oidc

  auth-server:
    build:
      context: ../auth-server
      dockerfile: Dockerfile
    container_name: auth-server
    ports:
      - 9000:9000
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/acl
      DB_USER: postgres
      DB_PASSWORD: S3cret
      JWT_PUBLIC_KEY: classpath:app.pub
      JWT_PRIVATE_KEY: classpath:app.key
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9000/.well-known/openid-configuration"]
      interval: 5s
      timeout: 3s
      retries: 10

  client-server:
    build:
      context: ../client-server
      dockerfile: Dockerfile
    container_name: client-server
    ports:
      - 8080:8080
    environment:
      REDIRECT_URI: "http://client-server:8080/login/oauth2/code/{registrationId}"
      ISSUER_URI: http://auth-server:9000
    depends_on:
      auth-server:
        condition: service_healthy

  resource-server:
    build:
      context: ../resource-server
      dockerfile: Dockerfile
    container_name: resource-server
    ports:
      - 9090:9090
    environment:
      ISSUER_URI: http://auth-server:9000
    depends_on:
      - auth-server
